steps:
  - name: 'gcr.io/cloud-builders/gradle:5.6.2-jdk-8'
    id: 'build'
    args: ['clean', 'build', 'jib', '--image=gcr.io/${PROJECT_ID}/people-$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy k8s'
    args: ['apply', '-f', '.ci/k8s']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'set image'
    args: [
      'set',
      'image',
      'deployment',
      'people',
      'people=gcr.io/${PROJECT_ID}/people-$COMMIT_SHA'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'

#  - name: "gcr.io/k8s-skaffold/skaffold"
#    args:
#      [
#        "gcloud",
#        "container",
#        "clusters",
#        "get-credentials",
#        "kube-cluster",
#        "--region",
#        "us-central1-a",
#        "--project",
#        "${PROJECT_ID}",
#      ]
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
#
#  - name: "gcr.io/k8s-skaffold/skaffold"
#    args: ["skaffold", "run"]