apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: people
deploy:
  kubectl:
    manifests:
      - ci/k8s/k8s.yaml
build:
  artifacts:
    - image: gcr.io/test-project-265502/people
      jib: {}
  googleCloudBuild:
    projectId: test-project-265502
